///<reference types="cypress" />


describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://www.saucedemo.com/v1/')
    cy.wait(2000)
    cy.get('[data-test="username"]').type("standard_user")
    cy.wait(2000)
    cy.get('[data-test="password"]').type("secret_sauce")
    cy.wait(2000)
    cy.get('#login-button').click()
    cy.wait(2000)
  cy.get(':nth-child(3) > .pricebar > .btn_primary').click()
  cy.wait(2000)
cy.get('.fa-layers-counter').click()
cy.wait(2000)
cy.get('.btn_action').click()
cy.wait(2000)
cy.get('[data-test="firstName"]').type("JAGDISH")
cy.wait(2000)
cy.get('[data-test="lastName"]').type("JANGID")
cy.wait(2000)
cy.get('[data-test="postalCode"]').type("411012")
cy.wait(2000)
cy.get('.btn_primary').click()
cy.wait(2000)
cy.get('.btn_action').click()
cy.wait(2000)
cy.get('.bm-burger-button > button').click()
cy.wait(2000)
cy.get('#logout_sidebar_link').click()
cy.wait(2000)
window.close()
  })
})